name: CI
on:
    push:
      branches: [ "main" ]

jobs:
    deploy:
      runs-on: [self-hosted]
      steps:
         - run: cd /var/www/html && git fetch --all && git reset --hard origin/main

      
