name: CI
on:
    push:
      branches: [ "main" ]

jobs:
    deploy:
      runs-on: [self-hosted]
      steps:
        - name: deploy 
          run: cd /var/www/html && git fetch && git reset --hard origin/main
