name: CI
on:
   # События, которые запускают jobs
    push:
      branches: [ "main" ]

# jobs запускаются параллельно, если не указана последовательность
jobs:
    deploy:
      runs-on: [self-hosted]
      steps:
         - uses: actions/checkout@v3

         - name: Run a one-line script
           run: echo Hello, world!

         - name: Run ifconfig
           run: ifconfig
